### ISSUE TITLE
Move "use strict" inside scope

### ISSUE THREAD

**Issue by larsthorup** [rbuckton/ReflectDecorators#14]
When bundling Reflect.js with other libraries for deployment purposes, the global "use strict" seems to cause problems because it automatically applies to all later libraries in the bundle. Would it be possible to nest the "use strict" inside all outermost global functions inside Reflect.js?

**Comment by jesperronn** [comment]
:+1:

**Comment by jesperronn** [comment]
This is great news!! @rbuckton could you also tag a release, so that dependent frameworks could upgrade?

**Comment by rbuckton** [comment]
I need to review to see if there are any other changes I want to take, buy I will publish a release shortly.

**Comment by brian428** [comment]
I realize this has been closed for a while, but I'm still seeing this. After running our bundle through UglifyJS, the 'use strict' block goes from this:
```
var Reflect;
(function (Reflect) {
    "use strict";
    // Load global or shim versions of Map, Set, and WeakMap
    var functionPrototype = Object.getPrototypeOf(Function);
   ...
   function decorate(decorators, target, targetKey, targetDescriptor) {
   ...
```

to this:
```
"use strict";var Reflect;!function(Reflect){function decorate(decorators,target,targetKey,targetDescriptor)
...
```

This causes problems since that "use strict" is now global.

I'm not entirely sure why this is happening, and not sure if it's the way the Reflect code is structured or if it is actually something odd that UglifyJS is doing (e.g. I'm not sure why it would strip out the IIFE like this).
