### ISSUE TITLE
No valid 'elements' option was specified for xxx

### ISSUE THREAD

**Issue by Rookian** [rbuckton/ReflectDecorators#51]
```ts
@JsonObject({ knownTypes: [EinheitentabellenEintrag, NachschlagetabellenEintrag]})
export class Nachschlagetabelle {
    public static get NACHSCHLAGETABELLE_TYPE(): string {
        return "Nachschlagetabelle";
    }

    @JsonMember
    tabellenname: string = "";

    @JsonMember({ elements: EinheitentabellenEintrag})
    test: EinheitentabellenEintrag[];

    @JsonMember({ elementType: NachschlagetabellenEintrag })
    ntEintraege: NachschlagetabellenEintrag[] = [];
}
```

Error:
No valid 'elements' option was specified for 'Nachschlagetabelle.test'.(…)

Why do I get the error message eventhough I specified a the elements option?

*edit: code block formatting - @rbuckton*

**Comment by rbuckton** [comment]
I'm not familiar with the library you are using that provides the `JsonObject` decorator. One possibility is that your use of `elements` is incorrect (to which I would refer you to review the documentation for the library in question). The other possibility is that `EinheitentabellenEintrag` is defined later in the file and is `undefined` at the time that its referenced, though if that were the case it should have resulted in a compile-time error due to the use of `EinheitentabellenEintrag` before its definition. 

Without more context I cannot ascertain the reason for the error.

**Comment by Rookian** [comment]
The
