### ISSUE TITLE
Incorrect environment detection in WeakMapPolyfill

### ISSUE THREAD

**Issue by wbuchwalter** [rbuckton/ReflectDecorators#8]
In CreateWeakMapPolyfill(), to detect if we are running under node, this code is used:

```
const isNode = typeof global !== "undefined" &&
  typeof module === "object" &&
  typeof module.exports === "object" &&
  typeof require === "function";
```

But when using tools which implement CommonJS API in the browser such as Webpack or Browserify, isNode will be incorrectly set to true.

We could replace the check by this one:

```
 const isNode = Object.prototype.toString.call(global.process) === '[object process]';
```

Related PR: #7 

Thanks!

**Comment by vinodsantharam** [comment]
+1

**Comment by GuillaumeSalles** [comment]
+1

**Comment by sectore** [comment]
Same issue by using [jspm](http://jspm.io/). 

Behind the scenes [SystemJS builder](https://github.com/systemjs/builder/) adds an `@empty` to `var nodeCrypto = isNode && require('@empty');` ([Reflect.ts#L1351](https://github.com/rbuckton/ReflectDecorators/blob/master/Reflect.ts#L1351)) for using an empty function. 

So the check of `nodeCrypto` ([Reflect.ts#L1399](https://github.com/rbuckton/ReflectDecorators/blob/master/Reflect.ts#L1399)) is failed: 
`Error evaluating XXX/jspm_packages/npm/reflect-metadata@0.1.0/Reflect.js
  TypeError: 'undefined' is not a function (evaluating 'nodeCrypto.randomBytes(size)')`

These issue can be fixed with #7 by @wbuchwalter as well.

-Jens

**Comment by wbuchwalter** [comment]
Hey @rbuckton , any feedback on this? Thanks!

**Comment by wbuchwalter** [comment]
Since this issue is kind of stalled, I made another npm package that doesn't have this issue to unblock thos affected: [reflect-metadata-env-fixed](https://www.npmjs.com/package/reflect-metadata-env-fixed)

**Comment by tamascsaba** [comment]
@rbuckton ????

**Comment by rbuckton** [comment]
My apologies, I've been out of the office for the past few weeks. I'm also clarifying any CLA requirements for this project before I can accept any pull requests.

**Comment by gdi2290** [comment]
:+1:

**Comment by rbuckton** [comment]
Closed #8 via #7.

**Comment by rolandjitsu** [comment]
@rbuckton how soon will this be released?

**Comment by rbuckton** [comment]
v0.1.1 has been published to npm.
